### ISSUE TITLE
affichage des mois 1 à 9

### ISSUE THREAD

**Issue by papo-o** [Tlinus/Meteo#1]
apparemment l'api a légèrement changée.
les mois de janvier à septembre ne sont plus 1. à 9.   mais 01 à 09
j'ai donc modifié légérement xhr.js pour que cela affiche le mois correctement
                    switch (json['fcst_day_'+j].date.substring(3,5)) {
                      case '01':
                        month = "Janvier";
                        break;
                      case '02':
                        month = "Fevrier";
                        break;
                      case '03':
                        month = "Mars";
                        break;
                      case '04':
                        month = "avril";
                        break;
                      case '05':
                        month = "mai";
                        break;
                      case '06':
                        month = "juin";
                        break;
                      case '07':
                        month = "juillet";
                        break;
                       case '08':
                        month = "août";
                        break;
                       case '09':
                        month = "septembre";
                        break;
                       case '10':
                        month = "octobre";
                        break;
                       case '11':
                        month = "novembre";
                        break;
                       case '12':
                        month = "décembre";
                        break;
                      default:
                        month = "";
                    }

**Comment by Tlinus** [comment]
Bonjour, 
Merci pour la remarque, cela à été corrigé, 
Le mois s'affiche correctement,
